name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PHP_VERSION: '8.0'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
    - name: Local PHP Security Checker
      uses: docker://pplotka/local-php-security-checker-github-actions
    # - name: Run PHPStan
    #   run: vendor/bin/phpstan analyse --no-progress
    # - name: Execute tests
    #   run: vendor/bin/phpunit
